// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/shinjuwu/TheNuts/internal/game"
	"github.com/shinjuwu/TheNuts/internal/game/adapter/ws"
	"github.com/shinjuwu/TheNuts/internal/infra/config"
	"github.com/shinjuwu/TheNuts/internal/infra/logger"
)

// Injectors from wire.go:

func InitApp(configPath string) (*App, error) {
	configConfig, err := config.LoadConfig(configPath)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	tableManager := game.NewTableManager()
	hub := ws.NewHub(zapLogger)
	ticketStore := ProvideTicketStore()
	handler := ws.NewHandler(hub, tableManager, ticketStore, zapLogger)
	jwtService := ProvideJWTService(configConfig)
	authHandler := ProvideAuthHandler(jwtService, ticketStore, configConfig, zapLogger)
	app := &App{
		Config:       configConfig,
		Logger:       zapLogger,
		TableManager: tableManager,
		Hub:          hub,
		WSHandler:    handler,
		JWTService:   jwtService,
		TicketStore:  ticketStore,
		AuthHandler:  authHandler,
	}
	return app, nil
}
